export const dashboardRoles = [
  'DEFAULT_ADMIN_ROLE',
  'BURN_ROLE',
  'FUND_ROLE',
  'MINT_ROLE',
  'WITHDRAW_ROLE',
  'NODE_OPERATOR_MANAGER_ROLE',
  'PAUSE_BEACON_CHAIN_DEPOSITS_ROLE',
  'RESUME_BEACON_CHAIN_DEPOSITS_ROLE',
  'REBALANCE_ROLE',
  'REQUEST_VALIDATOR_EXIT_ROLE',
  'TRIGGER_VALIDATOR_WITHDRAWAL_ROLE',
  'VOLUNTARY_DISCONNECT_ROLE',
  'VAULT_CONFIGURATION_ROLE',
  'COLLECT_VAULT_ERC20_ROLE',
  'NODE_OPERATOR_FEE_EXEMPT_ROLE',
  'NODE_OPERATOR_PROVE_UNKNOWN_VALIDATOR_ROLE',
  'NODE_OPERATOR_UNGUARANTEED_DEPOSIT_ROLE',
] as const;

export type RoleName = (typeof dashboardRoles)[number];
