export const StethEventsAbi = [
  { payable: true, stateMutability: 'payable', type: 'fallback' },
  {
    anonymous: false,
    inputs: [],
    name: 'StakingPaused',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'StakingResumed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: 'maxStakeLimit', type: 'uint256' },
      {
        indexed: false,
        name: 'stakeLimitIncreasePerBlock',
        type: 'uint256',
      },
    ],
    name: 'StakingLimitSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'StakingLimitRemoved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'reportTimestamp', type: 'uint256' },
      { indexed: false, name: 'preCLValidators', type: 'uint256' },
      { indexed: false, name: 'postCLValidators', type: 'uint256' },
    ],
    name: 'CLValidatorsUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'depositedValidators', type: 'uint256' }],
    name: 'DepositedValidatorsChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'reportTimestamp', type: 'uint256' },
      { indexed: false, name: 'preCLBalance', type: 'uint256' },
      { indexed: false, name: 'postCLBalance', type: 'uint256' },
      { indexed: false, name: 'withdrawalsWithdrawn', type: 'uint256' },
      {
        indexed: false,
        name: 'executionLayerRewardsWithdrawn',
        type: 'uint256',
      },
      { indexed: false, name: 'postBufferedEther', type: 'uint256' },
    ],
    name: 'ETHDistributed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'reportTimestamp', type: 'uint256' },
      { indexed: false, name: 'timeElapsed', type: 'uint256' },
      { indexed: false, name: 'preTotalShares', type: 'uint256' },
      { indexed: false, name: 'preTotalEther', type: 'uint256' },
      { indexed: false, name: 'postTotalShares', type: 'uint256' },
      { indexed: false, name: 'postTotalEther', type: 'uint256' },
      { indexed: false, name: 'sharesMintedAsFees', type: 'uint256' },
    ],
    name: 'TokenRebased',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'lidoLocator', type: 'address' }],
    name: 'LidoLocatorSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'amount', type: 'uint256' }],
    name: 'ELRewardsReceived',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'amount', type: 'uint256' }],
    name: 'WithdrawalsReceived',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'sender', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'referral', type: 'address' },
    ],
    name: 'Submitted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'amount', type: 'uint256' }],
    name: 'Unbuffered',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'executor', type: 'address' },
      { indexed: false, name: 'script', type: 'bytes' },
      { indexed: false, name: 'input', type: 'bytes' },
      { indexed: false, name: 'returnData', type: 'bytes' },
    ],
    name: 'ScriptResult',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'vault', type: 'address' },
      { indexed: true, name: 'token', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
    name: 'RecoverToVault',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'eip712StETH', type: 'address' }],
    name: 'EIP712StETHInitialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'from', type: 'address' },
      { indexed: true, name: 'to', type: 'address' },
      { indexed: false, name: 'sharesValue', type: 'uint256' },
    ],
    name: 'TransferShares',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'account', type: 'address' },
      { indexed: false, name: 'preRebaseTokenAmount', type: 'uint256' },
      { indexed: false, name: 'postRebaseTokenAmount', type: 'uint256' },
      { indexed: false, name: 'sharesAmount', type: 'uint256' },
    ],
    name: 'SharesBurnt',
    type: 'event',
  },
  { anonymous: false, inputs: [], name: 'Stopped', type: 'event' },
  { anonymous: false, inputs: [], name: 'Resumed', type: 'event' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'from', type: 'address' },
      { indexed: true, name: 'to', type: 'address' },
      { indexed: false, name: 'value', type: 'uint256' },
    ],
    name: 'Transfer',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'owner', type: 'address' },
      { indexed: true, name: 'spender', type: 'address' },
      { indexed: false, name: 'value', type: 'uint256' },
    ],
    name: 'Approval',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'version', type: 'uint256' }],
    name: 'ContractVersionSet',
    type: 'event',
  },
] as const;
