export type HeadMessage =
  | 'Provider:'
  | 'Contracts:'
  | 'Balances:'
  | 'Utils:'
  | 'Views:'
  | 'Call:'
  | 'Error:'
  | 'LOG:'
  | 'Cache:'
  | 'Init:'
  | 'Permit:'
  | 'Events:'
  | 'Statistic:'
  | 'Rewards:'
  | 'Deprecation:'
  | 'API:';
