name: Check all
on:
  pull_request:
jobs:
  check-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          RPC_PROVIDER_URL_1: ${{ vars.RPC_PROVIDER_URL_1 }}
          RPC_PROVIDER_URL_5: ${{ vars.RPC_PROVIDER_URL_5 }}
          WALLETCONNECT_PROJECT_ID: ${{ vars.WALLETCONNECT_PROJECT_ID }}
      - name: Check types
        run: yarn types

      - name: Tests
        run: yarn test
